(function(b,d,k){function e(a,f){this.element=b(a);this.options=b.extend(!0,{},m,f);this.init()}var m={show:{google:!0,facebook:!0,twitter:!0,reddit:!0,linkedin:!0,meneame:!0},title:k.title,url:k.location.href,base:"/wp-content/plugins/ic-besocial",tracking:!0,wrapper:"div",buttons:{google:{lang:"es",size:"standard"},facebook:{label:"Compartir en Facebook",title:"Se ha compartido {count} veces.",url:"",width:850,height:500},twitter:{label:"Twittear",title:"{count} personas han twitteado esto.",url:"",
via:"",width:650,height:360},reddit:{label:"Enviar a Reddit",title:"Puntuaci\u00f3n {count}.",url:"",width:550,height:550},linkedin:{label:"Compartir en LinkedIn",title:"Se ha compartido {count} veces.",url:"",width:550,height:550},meneame:{label:"Menear",title:"{count} personas han meneado esto.",url:"",ok:"Entrada pendiente de aprobarse.",ko:"No se acept\u00f3 la entrada.",width:850,height:500}}},h=function(a,f){return(f||"")+"be-social-"+a},n={facebook:'https://graph.facebook.com/fql?q=select%20%20total_count%20from%20link_stat%20where%20url="{url}"&callback=?',
twitter:"http://cdn.api.twitter.com/1/urls/count.json?url={url}&callback=?",reddit:"{base}/reddit.php?url={url}",linkedin:"http://www.linkedin.com/countserv/count/share?format=jsonp&url={url}&callback=?",meneame:"http://www.meneame.net/api/url.php?url={url}&jsonp=?"},o={facebook:function(a){return"http://www.facebook.com/sharer.php?u="+encodeURIComponent(a.url)+"&t="+a.title},twitter:function(a){return"https://twitter.com/intent/tweet?text="+encodeURIComponent(a.title)+"&url="+encodeURIComponent(a.url)+
(""!==a.buttons.twitter.via?"&via="+a.buttons.twitter.via:"")},reddit:function(a){return"http://www.reddit.com/submit?url="+encodeURIComponent(a.url)+"&title="+encodeURIComponent(a.title)},linkedin:function(a){return"https://www.linkedin.com/cws/share?url="+encodeURIComponent(a.url)+"&token=&isFramed=true"},meneame:function(a){return""!==a.buttons.meneame.url?a.buttons.meneame.url:"http://www.meneame.net/submit.php?url="+encodeURIComponent(a.url)+"&title="+encodeURIComponent(a.title)}},l={facebook:{site:"Facebook",
action:"Like"},twitter:{site:"Twitter",action:"Tweet"},reddit:{site:"Reddit",action:"Share"},linkedin:{site:"LinkedIn",action:"Share"},meneame:{site:"Meneame",action:"Meneo"}},j={loading:!1,script:function(a){if(!1===j.loading)j.loading=!0,d.___gcfg={lang:a},b("head").append('<script type="text/javascript" async="async" src="https://apis.google.com/js/plusone.js">')}};e.prototype.init=function(){var a=this;b.each(this.options.show,function(f,g){if(!0===g)if(a.element.prepend("<"+a.options.wrapper+
' class="'+h("button")+" "+h(f)+'"></'+a.options.wrapper+">"),"google"===f)a.plusone();else try{a.count(f)}catch(b){}})};e.prototype.plusone=function(){var a=this.options.buttons.google;this.element.find(h("google",".")).html('<div class="g-plusone" data-size="'+a.size+'" data-href="'+this.options.url+'"></div>');j.script(a.lang)};e.prototype.count=function(a){var f=this,g=0,d=n[a].replace("{url}",this.options.url).replace("{base}",this.options.base);b.getJSON(d,function(c){switch(a){case "twitter":"undefined"!==
typeof c.count&&(g=parseInt(c.count,10));break;case "facebook":"undefined"!==typeof c.data[0].total_count?g=parseInt(c.data[0].total_count,10):"undefined"!==typeof c.shares&&(g=parseInt(c.shares,10));break;case "reddit":if(0<c.data.children.length)for(var b=0,d=c.data.children.length;b<d;b++)g+=parseInt(c.data.children[b].data.score,10);break;case "linkedin":"undefined"!==typeof c.count&&(g=parseInt(c.count,10));break;case "meneame":b=f.options.buttons.meneame;d=0;if("OK"===c.status){for(var c=c.data,
d="",e=!1,i=0,h=c.length;i<h;i++)if(b.url=c[i].url,"published"===c[i].status||"queued"===c[i].status){d=parseInt(c[i].votes,10)+parseInt(c[i].anonymous,10);break}else if("pendent"===c[i].status){e=!0;break}if(""===d)e?(b.title=b.ok,d=":-)"):(b.title=b.ko,d=":-(")}g=d}f.render(a,g)})};e.prototype.render=function(a,b){var d=this,e=this.options.buttons[a],c=e.title;e.url=o[a](this.options);"number"===typeof b&&(c=c.replace("{count}",b),b=this.shorter(b));this.element.find(h(a,".")).html('<a class="'+
h("link")+'" href="'+e.url+'" title="'+e.label+'">'+e.label+'</a> <span class="'+h("count")+'" title="'+c+'">'+b+"</span>").on({click:function(){return d.popup(a)}})};e.prototype.shorter=function(a){1E6<=a?a=(a/1E6).toFixed(2)+"M":1E3<=a&&(a=(a/1E3).toFixed(1)+"k");return a};e.prototype.popup=function(a){var b=this.options.buttons[a];d.open(b.url,"","toolbar=0, status=0, scrollbars=1, width="+b.width+", height="+b.height);!0===this.options.tracking&&"undefined"!==typeof _gaq&&_gaq.push(["_trackSocial",
l[a].site,l[a].action]);return!1};b.fn.icBeSocial=function(a){return this.each(function(){b.data(this,"plugin_icBeSocial")||b.data(this,"plugin_icBeSocial",new e(this,a))})}})(jQuery,window,document);(function(b){b(".be-social").each(function(){var d=b(this);d.append('<ul class="be-social-buttons"></ul>').find(".be-social-buttons").icBeSocial({wrapper:"li",url:d.data("url"),base:d.data("base"),title:d.data("title"),tracking:d.data("track"),show:d.data("show"),buttons:{twitter:{via:d.data("via")}}})})})(jQuery);
